language: node_js
node_js:
  - '8'
branches:
  only:
    - master
    - develop
    - '/^v.*$/'
before_script:
  - npm install
before_deploy:
  - npm run prerelease
deploy:
  - provider: npm
    skip_cleanup: true
    edge: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: JJfHY/1x06Nu1m7yrj5XooLeooXUFTp6ZLwHIVuAyC769nQpX8zQtkhNxiwp1qZKjHptNRF7v9u0p1K2Zv+0ChjDNWGLdrHOk6bOT76OVnv2+OmJNQwI9S6g1MxGNt9lmX5UXZMbqe/A9hugqV3dHgPd2ili1pEBjOFgpkfy1hXvDCgDN8usmqoJ4rIE7X4jWIMpcvioUB1Qe387RC4lqAP9XPpZtwuAUe/v31+Phus0gfoc/dBTaVNbTC6IENZsXZ+3DpDm06xzQyjsoyfc8ppn36911/N+HC6Gt2aqWHqE+SXYkhd1nfwbroya8lRAJxHcyAf2Bkh8rNloCskY5O+6u31QF+u4BeSJyeYYYDmZd7vdxKVdvMqSZmzPrqY4i50RGBUJ78Wg3JMpG1gsnDcwpcoiXmaiHtcBtK7LxsSV6/NINpaNGhT6AqtV+ngVZTfEwr/MvM14g+PvH3yllj24NTSyCEzP3fjlvlmzV/+RbDiVnhvPRh9WPGRhiCW54VLMqW6qgNVDZlahRKDAPpn4EvN9zhK62/YdKsKo4qjbZmLlo5XckQn2SeYrhlYnO9ET9QAGtMMcoI0+tRg52N4EtUrHR6PiU5jzoO++RXBx9Mcq2V5DzA/lq+zatk7EGl4MChBNMI36sixhTTNdp3kKFy5Hkw3eXS/WTcuIjcw=
    on:
      tags: true
      repo: higlass/higlass-vcf
      branch: master
  - provider: releases
    skip_cleanup: true
    email: pkerpedjiev@gmail.com
    api_key:
      secure: h3ZxP8Go0shUIFSBQyuwdR8mgZ7HSCdh7tJlyPzNdgUj07wGueImavBihju6OhctcJexSLFSohRXHmr1ru1fM0jEpuYY77VceQKixCVw7R1ufUuzS9zTs9kFAUEOF7Nb6N1q5U7ArkHBMCaSHUg8iiu9JFPmu99kI/akS63v5N9SkNq9+l/3kcHbjRMOY2+lWHkN3R8TJs03wKorfjsPsjenPH1t34bHFaoHmOuwwJE6ruGLXGAIwH2kF2GD01qacqPZflIXRRRyyGtIxKHiu17aBLb91xPmjIQUjzUvShx8sMqYkxaJqprWxyZji64qMXNj8C4bdEbqWk8xAkWOu5TnC1nuVueu5iFcHq6xxe5DpdBTVbNb+dxQOzyzyKlHbapmeP4WPw6hDRIsS72rFhI526L1+JdrA+u1S2PrHhQIkjLDxLk3rleTzQnZa3LaZosvm76O1L2gqTQOawsO9q1AqMi4vdALIRz8UM3dBSsYWWh3gL8wmFXGgkGykZDi3rpdp+hX0io8X9B8Z9psEg/H066dz7Xdv8VjtPr9jiURbNQh1bxsrhSREt4egDsc+LodupL1zokTWq7upQz0GKbkWhyqsWDMhgoYoiSSHA4hGMsInGd2fU1H3WHWv0tnnqGDpEYcf29PiKMRLTl/iJDgLCBUWmrnw9qn9eQ/VlQ=
    file: dist.zip
    on:
      repo: higlass/higlass-vcf
